name: PyPI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: [main]

jobs:
  build-dist:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: python3 -m pip install build
    - name: Build a binary wheel a source tarball
      run: python -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    # only publish to PyPI on tag pushes
    if: github.event_name == 'push' &&  startsWith(github.ref, 'refs/tags/')
    needs:
    - build-dist
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/sphinxpacket
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

